# Dependencies
markdown: 				redcarpet

# Permalinks
permalink:        /:title/

# Setup
title:            Guia Xarxes Socials
tagline:          'Generalitat de Catalunya'
description:      'Guia de xarxes socials de la Generalitat de Catalunya'
url:          		http://gencat.github.io/guia
baseurl:          		http://gencat.github.io/guia


# Gems
gems:
  - jekyll-sitemap
